### ISSUE TITLE
[BUG] IDOR

### ISSUE THREAD

**Issue by nk521** [rshrc/NSP#111]
**IDOR is there on chat and on update info page**

**To reproduce the update info page bug**
* `https://thensp.pythonanywhere.com/account/profile/`+ID number+`/edit_details`
* Form will submit itself with a response of 302

**To reproduce the chat bug**
* `https://thensp.pythonanywhere.com/account/chat/`+Username

**Expected behavior**
>  To talk to someone you need to follow them and the other user must be following you too. 

This is what `https://thensp.pythonanywhere.com/account/chat/` says.. but IDOR is present

**Desktop (please complete the following information):**
* Arch running Firefox 61.0.1

**Additional context**
To find which ID number is of whom, sail to `https://thensp.pythonanywhere.com/account/social/unfollow/`+ID

**Comment by gjergjk71** [comment]
@nk521 Thanks for reporting the bug, kinda with I'd seen your latest issues sooner.
