### ISSUE TITLE
Number of interested people in ProjectDetail model does not increase

### ISSUE THREAD

**Issue by rshrc** [rshrc/NSP#7]
# in views.py
def ProjectInterestedCounter(request):
    project = ProjectDetail.objects.get(project_name=project_name)
    project.people_interested = project.people_interested + 1
    print("Value Upldated")

this is called on the button click of check in listprojects.html

**Comment by rshrc** [comment]
yes, but in the templates, can loop over it, need to fix it too.. I have dropped you a text on messenger

**Comment by gjergjk71** [comment]
Should be fixed with pull request #10
