### ISSUE TITLE
Notifications on Own/Interested projects.

### ISSUE THREAD

**Issue by svr8** [rshrc/NSP#71]
Didn't know someone added a solution to issue on my project. Need notifications.
Also, If someone mentions my username anywhere, I want to know about it too.

**Comment by gjergjk71** [comment]
I completed notifications for follows, issues/solutions created on your projects with #90 , do you think owner of the project should be notified of comments on their projects issues/solutions or would it be annoying?

**Comment by svr8** [comment]
Oh great! ..and yeah it would be annoying, how about an option to follow/unfollow notifications on a project like GitHub has 'watch' option.

**Comment by gjergjk71** [comment]
@svr8 I'll probably go for having watch option True as default for the users who created issue/solution and leave a button for anyone who wants to watch/unwatch issue/solution.
